# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run test"
  lane :tests do
    get_certificates
    get_provisioning_profile
    gym
    upload_to_testflight    
#   run_tests(workspace: "MatchProvision.xcworkspace",
#              devices: ["iPhone 6s"],
#              scheme: "MatchProvision")
  end

 # desc "Push a new beta build to TestFlight"
 # lane :beta do
 #   build_app
 #   get_certificates
 #   get_provisioning_profile
 #   gym
 #   upload_to_testflight
 #   sync_code_signing(type: "appstore") 
 #   build_app(scheme: "MatchProvision",
 #             workspace: "Example.xcworkspace",
 #             include_bitcode: true)
 #   upload_to_testflight(skip_waiting_for_build_processing: true)
 # end
end
